name: S3 Cache action
description: Cache files on S3 with branch-specific paths for granular permissions
author: SonarSource

inputs:
  path:
    description: A list of files, directories, and wildcard patterns to cache and restore
    required: true
  key:
    description: An explicit key for restoring and saving the cache
    required: true
  restore-keys:
    description: An ordered list of prefix-matched keys to use for restoring stale cache if no cache hit occurred for key
  upload-chunk-size:
    description: The chunk size used to split up large files during upload, in bytes
  enableCrossOsArchive:
    description: An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
    default: false
  fail-on-cache-miss:
    description: Fail the workflow if cache entry is not found
    default: false
  lookup-only:
    description: Check if a cache entry exists for the given input(s) (key, restore-keys) without downloading the cache
    default: false
  environment:
    description: Environment to use (dev or prod)
    default: prod

outputs:
  cache-hit:
    description: A boolean value to indicate an exact match was found for the primary key
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Authenticate to AWS
      shell: bash
      env:
        POOL_ID: ${{ inputs.environment == 'prod' && 'eu-central-1:511fe374-ae4f-46d0-adb7-9246e570c7f4' || 'eu-central-1:3221c6ea-3f67-4fd8-a7ff-7426f96add89' }}
        AWS_ACCOUNT_ID: ${{ inputs.environment == 'prod' && '275878209202' || '460386131003' }}
        IDENTITY_PROVIDER_NAME: token.actions.githubusercontent.com
        AUDIENCE: cognito-identity.amazonaws.com
        AWS_REGION: eu-central-1
      run: |
        # Get GitHub Actions ID token using script
        ACCESS_TOKEN=$("$GITHUB_ACTION_PATH/scripts/get-github-token.sh")
        echo "::add-mask::$ACCESS_TOKEN"

        # Get Identity ID
        identityId=$(aws cognito-identity get-id \
        --identity-pool-id "$POOL_ID" \
        --account-id "$AWS_ACCOUNT_ID" \
        --logins '{"'"$IDENTITY_PROVIDER_NAME"'":"'"$ACCESS_TOKEN"'"}' \
        --query 'IdentityId' --output text)

        # Validate Identity ID was obtained
        if [[ "$identityId" == "null" || -z "$identityId" ]]; then
          echo "::error::Failed to obtain Identity ID from Cognito Identity Pool"
          echo "::error::Check identity pool configuration and IAM roles"
          exit 1
        fi

        # Get and validate AWS credentials
        awsCredentials=$(aws cognito-identity get-credentials-for-identity \
        --identity-id "$identityId" \
        --logins '{"'"$IDENTITY_PROVIDER_NAME"'":"'"$ACCESS_TOKEN"'"}')

        AWS_ACCESS_KEY_ID=$(echo "$awsCredentials" | jq -r ".Credentials.AccessKeyId")
        AWS_SECRET_ACCESS_KEY=$(echo "$awsCredentials" | jq -r ".Credentials.SecretKey")
        AWS_SESSION_TOKEN=$(echo "$awsCredentials" | jq -r ".Credentials.SessionToken")

        echo "::add-mask::$AWS_ACCESS_KEY_ID"
        echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
        echo "::add-mask::$AWS_SESSION_TOKEN"

        if [[ "$AWS_ACCESS_KEY_ID" == "null" || -z "$AWS_ACCESS_KEY_ID" ]]; then
          echo "::error::Failed to obtain AWS Access Key ID"
          exit 1
        fi

        if [[ "$AWS_SECRET_ACCESS_KEY" == "null" || -z "$AWS_SECRET_ACCESS_KEY" ]]; then
          echo "::error::Failed to obtain AWS Secret Access Key"
          exit 1
        fi

        if [[ "$AWS_SESSION_TOKEN" == "null" || -z "$AWS_SESSION_TOKEN" ]]; then
          echo "::error::Failed to obtain AWS Session Token"
          exit 1
        fi

        echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN" >> $GITHUB_ENV

    - name: Prepare cache keys
      shell: bash
      id: prepare-keys
      run: |
        # Use GITHUB_HEAD_REF for PR events, GITHUB_REF for push events
        BRANCH_NAME="${GITHUB_HEAD_REF:-$GITHUB_REF}"
        BRANCH_KEY="${BRANCH_NAME}/${{ inputs.key }}"
        echo "branch-key=${BRANCH_KEY}" >> $GITHUB_OUTPUT

        # Process restore keys: keep branch-specific keys and add fallback to default branch
        if [ -n "${{ inputs.restore-keys }}" ]; then
          RESTORE_KEYS=""
          # First, add branch-specific restore keys
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              if [ -n "$RESTORE_KEYS" ]; then
                RESTORE_KEYS="${RESTORE_KEYS}"$'\n'"${BRANCH_NAME}/${line}"
              else
                RESTORE_KEYS="${BRANCH_NAME}/${line}"
              fi
            fi
          done <<< "${{ inputs.restore-keys }}"

          # Get the default branch dynamically using GitHub API
          DEFAULT_BRANCH=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/repos/${{ github.repository }}" | \
            jq -r '.default_branch')

          # Then, add default branch fallback keys (with dynamic default branch)
          while IFS= read -r line; do
            if [ -n "$line" ]; then
              RESTORE_KEYS="${RESTORE_KEYS}"$'\n'"refs/heads/${DEFAULT_BRANCH}/${line}"
            fi
          done <<< "${{ inputs.restore-keys }}"

          echo "branch-restore-keys<<EOF" >> $GITHUB_OUTPUT
          echo "$RESTORE_KEYS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        fi

    - name: Cache on S3
      uses: runs-on/cache@50350ad4242587b6c8c2baa2e740b1bc11285ff4 # v4.3.0
      id: cache
      env:
        RUNS_ON_S3_BUCKET_CACHE: sonarsource-s3-cache-${{ inputs.environment }}-bucket
        AWS_DEFAULT_REGION: eu-central-1
        AWS_REGION: eu-central-1
      with:
        path: ${{ inputs.path }}
        key: ${{ steps.prepare-keys.outputs.branch-key }}
        restore-keys: ${{ steps.prepare-keys.outputs.branch-restore-keys }}
        upload-chunk-size: ${{ inputs.upload-chunk-size }}
        enableCrossOsArchive: ${{ inputs.enableCrossOsArchive }}
        fail-on-cache-miss: ${{ inputs.fail-on-cache-miss }}
        lookup-only: ${{ inputs.lookup-only }}

branding:
  icon: upload-cloud
  color: blue
